apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job
spec:
# 顺序执行该job五次,最多允许两个pod同时运行
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job
