apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
  - image: harbor.test.h.cn/rke-lab/fortune:env1
    imagePullPolicy: IfNotPresent
    env: 
    - name: INTERVAL
      value: "30"
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
    emptyDir: {}
