apiVersion: v1
kind: Pod
metadata:
  name: fortune2s
spec:
  containers:
  - image: harbor.test.h.cn/rke-lab/fortune:args1
    args: ["2"]
    name: html-generater
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: 
      medium: Memory
